### ISSUE TITLE
Make it possible to convert without importing React

### ISSUE THREAD

**Issue by tchap** [jeffbernst/steem-markdown#1]
Hi,

I would love to use this package with Angular, is there any reason why the converting logic is coupled with React so tightly? It would be really handy to just import a function to turn anything into HTML without importing React in the same file...

I guess it would mean to split `getHtml` into multiple functions and then just call these functions in `getHtml` based on `returnType` to stay compatible...

What do you think?

**Comment by jeffbernst** [comment]
Yeah, honestly when I started making this module I really just wanted to make a plug & play type of thing that could work for anyone, so I played around with the functions for a little while but wasn't able to get it to work. I just wanted to quickly see if it could work so I ended up just pulling in all of the dependencies including React. 

Can you see what the solution would be to decouple it? I don't have time right now to look through it but could make some quick updates or merge pull requests.
